### ISSUE TITLE
Diagrams get crunched if rendered by CI

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/krater#2]
This happened to @jonsterling in https://github.com/jonsterling/math producing charming results such as

![image](https://user-images.githubusercontent.com/2499655/148556099-8fe286c7-95e3-4435-9f75-56c3e1ea4298.png)

(source: https://categorytheory.zulipchat.com/#narrow/stream/241990-general.3A-values/topic/goals.20and.20questions/near/267181997)

The problem is twofold:
1. the first compilation happened without `ghostscript` (a hard requirement for the conversion happening via `dvisvgm`)
2. following compilations were skipped (even when I tried adding the dependency) because the sourcecode MD5 didn't change

The solution is simple:
1. add the system dependency -> https://github.com/paolobrasolin/krater/commit/7db5f9625630b382f62d310adf195bc09554c025
2. clear the cache artifacts

There's still no nice button to empty the cache, though!
We can easily circumvent that by sketching another essential feature...

Some files will modify the compilation output even if the sources (hence their hashes) don't change. Therefore, changes in these files should invalidate the cache. Let's start by including TeX Live configuration in the list of such files -> https://github.com/paolobrasolin/krater/commit/2cad5c678cfbb5ac09cb1c355d1bfc33662cc320

Whatever solution we think of for #1 we'll need to consider this side effect.
In fact, you'll want to include your macro files in the list @jonsterling.

**Comment by jonsterling** [comment]
@paolobrasolin I just moved to a different machine (which does have Ghostscript installed) and this is happening locally. Do you have any suggestions for how I should proceed?

**Comment by jonsterling** [comment]
Update: Although Ghostscript is installed, it seems not to be recognised by `dvisvgm`, since when I manually run `dvisvgm --pdf ...` I get:

> ERROR: Ghostscript is required to process PDF files.

I think the problem is that Homebrew doesn't actually install `libgs` properly; obviously this is neither the fault of your code nor the fault of `dvisgvm`, but nonetheless it remains a pretty serious obstacle for ordinary people to use it. I wonder what we should do.

**Comment by jonsterling** [comment]
I've added some instructions to my README for Mac users who face this problem: https://github.com/jonsterling/math/commit/edcc1886f378503421e8d678eb7d75c87b831f38

**Comment by paolobrasolin** [comment]
I think the best we can do is document the snags with the various OSs.
I have no MacOS machine right now, so thanks for the research! :heart: 
Since this is a general issue with `jekyll-antex` I'll steal the info for its documentation.
Also, I'll try to extend its CI to cover MacOS if I can.
