### ISSUE TITLE
Include a simple way to deploy locally without CI

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/krater#3]

**Comment by paolobrasolin** [comment]
See https://github.com/paolobrasolin/krater#local-deployment

cc @jonsterling you can avoid keeping the build artifacts in your `main` branch like this (I prefer it).

**Comment by jonsterling** [comment]
@paolobrasolin Wow thanks!! This works great!

Btw I ended up having to use some other commands (http://sangsoonam.github.io/2019/02/08/using-git-worktree-to-deploy-github-pages.html) to get the `gh-pages` branch started over from scratch, as I'd messed it up somehow..
